### ISSUE TITLE
Importing Package

### ISSUE THREAD

**Issue by PR3R00T** [Dextroz/virustotal-python#10]
Hello, 
I imported your package into my code however I get a error:
Traceback (most recent call last):         
  File "./VTupload.py", line 4, in <module>                 
    from virustotal import Virustotal                
ModuleNotFoundError: No module named 'virustotal'   

I checked the pip package folder: /usr/local/lib/python3.7/dist-packages/
however it displays your package as virustotal_python

I managed to fix it but doing "from virustotal_python import VIrustotal"

You experiencing this issue too?

**Comment by ghost** [comment]
Hello @PR3R00T 

Thanks for submitting this issue!

You are correct that `from virustotal import Virustotal` is from `examples.py` is incorrect for importing the package. This is a mistake I have made in the documentation.

The correct method to import is `from virustotal_python import Virustotal` as you have said.

I will fix this documentation issue in the next update! 👍

**Comment by ghost** [comment]
Fixed in #11
