### ISSUE TITLE
message": "X-Apikey header is missing"

### ISSUE THREAD

**Issue by lacondeguy** [Dextroz/virustotal-python#40]
Hello, I can't figure out why this error occurs.

```
from config import api_key

def file_scan(file_path):
    files = {"file": (os.path.basename(file_path), open(os.path.abspath(file_path), "rb"))}
    with virustotal_python.Virustotal(api_key) as vtotal:
            resp = vtotal.request("files", files=files, method="POST")
            data = json.dumps(resp.data)
            message = json.loads(data)
    return message
```
    
I even substituted a key instead of a variable, still an error. Like this:
`with virustotal_python.Virustotal('9xxxxxxxxxxxxxxxxxxxxxxxxxxxx17g') as vtotal:`

Error:
![22](https://user-images.githubusercontent.com/97394658/228198074-b7f76b9d-334e-41fa-b4de-7235708c5562.png)

**Comment by dbrennand** [comment]
Hi @lacondeguy - Thanks for checking out the library.

Someone had a similar issue in #35 and it was an issue with how they were importing their API key.

I'm unable to replicate this issue on my end. Here is my setup (all files in the same directory):

```python
# config.py
API_KEY = "Insert API Key"
```

```python
# test.py
from config import API_KEY
import virustotal_python
import os

def file_scan(file_path):
    files = {"file": (os.path.basename(file_path), open(os.path.abspath(file_path), "rb"))}
    with virustotal_python.Virustotal(API_KEY) as vtotal:
        resp = vtotal.request("files", files=files, method="POST")
    return resp.data

print(file_scan("/path/to/my/file.txt"))
```

```
(sandbox) ➜  sandbox python --version              
Python 3.11.1
(sandbox) ➜  sandbox pip list | grep virustotal   
virustotal-python  1.0.2
(sandbox) ➜  sandbox python test.py
{'type': 'analysis', 'id': 'redacted', 'links': {'self': 'redacted'}}
```

**Comment by lacondeguy** [comment]
![100](https://user-images.githubusercontent.com/97394658/228612296-c0f17ce0-8785-4e77-be2a-0b1129fd6838.png)

There is still a problem, even copying exactly your code. I tried to import the same way as you and type the key manually. 

The problem is only when i check the files.. but everything works fine when i check the url and i use the same key.

**Comment by dbrennand** [comment]
Hi, 

I'm a bit confused? In your PyCharm terminal the script executed successfully.

**Comment by lacondeguy** [comment]
Hello, If you open the link from the terminal, you will get the following result:
```
{
    "error": {
        "message": "X-Apikey header is missing",
        "code": "AuthenticationRequiredError"
    }
}
```

**Comment by dbrennand** [comment]
> Hello, If you open the link from the terminal, you will get the following result:
> 
> ```
> {
>     "error": {
>         "message": "X-Apikey header is missing",
>         "code": "AuthenticationRequiredError"
>     }
> }
> ```

Oh! I see what you're trying to do now 😆 Sorry that wasn't clear from your initial message.

You shouldn't use the link directly.

You need to perform a subsequent API request using the `id` value to query the result of the analysis. Use the [analyses](https://developers.virustotal.com/reference/analysis) endpoint.

Expanding on the previous example slightly:

```python
scan_id = file_scan("./file.txt")['id']
vtotal = virustotal_python.Virustotal(API_KEY=API_KEY)
resp = vtotal.request(f"analyses/{scan_id}")
print(resp.data)
```

**Comment by lacondeguy** [comment]
Sorry :) now I understand, thanks

**Comment by rmaues** [comment]
Hi @dbrennand,
I'm creating code to make a query on the API and I've been getting the same error message as the one pasted above. This is my code. Can you help me with this? Where is the error?

import sys
import webbrowser
import requests

url_endpoint = "https://www.virustotal.com/api/v3/files"

file_name = sys.argv[1]

files = {'file': (file_name, open(file_name, "rb"), "application/pdf")}

headers = {
    "accept": "application/json",
    "x-apikey": "MY_API_KEY"
}

response = requests.post(url_endpoint, files=files, headers=headers)

json_fields = response.json()

print(json_fields)

id_field = json_fields['data']['id']

print(id_field)

result = "https://www.virustotal.com/api/v3/analyses/" + id_field

webbrowser.open_new_tab(result)

**Comment by dbrennand** [comment]
> Hi @dbrennand,
> 
> I'm creating code to make a query on the API and I've been getting the same error message as the one pasted above. This is my code. Can you help me with this? Where is the error?
> 
> 
> 
> import sys
> 
> import webbrowser
> 
> import requests
> 
> 
> 
> url_endpoint = "https://www.virustotal.com/api/v3/files"
> 
> 
> 
> file_name = sys.argv[1]
> 
> 
> 
> files = {'file': (file_name, open(file_name, "rb"), "application/pdf")}
> 
> 
> 
> headers = {
> 
>     "accept": "application/json",
> 
>     "x-apikey": "MY_API_KEY"
> 
> }
> 
> 
> 
> response = requests.post(url_endpoint, files=files, headers=headers)
> 
> 
> 
> json_fields = response.json()
> 
> 
> 
> print(json_fields)
> 
> 
> 
> id_field = json_fields['data']['id']
> 
> 
> 
> print(id_field)
> 
> 
> 
> result = "https://www.virustotal.com/api/v3/analyses/" + id_field
> 
> 
> 
> webbrowser.open_new_tab(result)

Hi @rmaues 

You're not using this Python library anywhere in your code. If you used this library there wouldn't be any need to craft the request yourself, this is all handled by the library.

The reason you're seeing the error is because when opening the `result` URL in your browser, the VirusTotal API expects the `x-apikey` in the request headers. Instead of opening this URL in your browser, use a HTTP GET request.

**Comment by rmaues** [comment]
@dbrennand 
Thank you.
