### ISSUE TITLE
how to download file from vt?

### ISSUE THREAD

**Issue by ohyeah521** [Dextroz/virustotal-python#41]
my code ,but it's not work.

```
def download_file(hash: str, dir: str) -> None:
    resp = vtotal.request(f"files/{hash}/download")
    if resp.status_code == 200:
        content_type = resp.headers.get("Content-Type")
        content = None
        if content_type == "application/octet-stream":
            content = resp.content
        elif content_type == "application/json":
            content = resp.json()
        elif content_type == "application/vnd.android.package-archive":
            content = resp.data


        file_name = f"{hash}.virus"
        file_path = os.path.join(dir, file_name)
        with open(file_path, "wb") as f:
            f.write(content)
        print(f"Downloaded {file_name} to {dir}")
    else:
        raise virustotal_python.VirustotalError(f"File download failed: {resp.status_code}")
```

**Comment by dbrennand** [comment]
What is the exact error you're seeing?

**Comment by ohyeah521** [comment]
> What is the exact error you're seeing?

  File "C:\Python3\lib\site-packages\virustotal_python\virustotal.py", line 171, in data
    return self.json().get("data", None)
  File "C:\Python3\lib\site-packages\virustotal_python\virustotal.py", line 219, in json
    return self.response.json(**kwargs)
  File "C:\Python3\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)









From the error message, it seems that binary data was returned and the code was processed using JSON, resulting in a crash.

Fix:

`content = resp.requests_response.content `
