### ISSUE TITLE
Extracting Family Labels From Binaries

### ISSUE THREAD

**Issue by lkurlandski** [Dextroz/virustotal-python#42]
Hi,

I wrote a similar bit of code myself to label binaries with the VT API. Thankfully, I can now just use yours, which is much more developed! Anyway, when I upload a binary to VT's web interface, I get the following information:

Popular threat label: [trojan.gafgyt/ddos](https://www.virustotal.com/gui/search/engines:trojan%20AND%20engines:gafgyt%20AND%20engines:ddos%20AND%20engines:lightaidra)

Threat categories:

- [trojan](https://www.virustotal.com/gui/search/engines%253Atrojan)

Family labels:

- [gafgyt](https://www.virustotal.com/gui/search/engines%253Agafgyt)
- [ddos](https://www.virustotal.com/gui/search/engines%253Addos)
- [lightaidra](https://www.virustotal.com/gui/search/engines%253Alightaidra)

I would really like to get this same information from the API but I am having trouble with it. I'll spare you the details of why I'm finding this challenging. Is there any way one can do this with your package?

**Comment by dbrennand** [comment]
Hi @lkurlandski

I've not retrieved threat categories or family labels from the API before. However, if it's available in the VT web interface, then it should be available via the API.

> when I upload a binary to VT's web interface, I get the following information

Would you be able to provide the exact URL where you see this information please? 🙂 

Also, just so I'm understanding correctly, you want to use the package to upload binary(s), and then retrieve the analysis of the binary? Ideally this analysis would contain the threat categories and family labels?

**Comment by lkurlandski** [comment]
Hi,

Thanks for getting back so quickly! Yeah, it does seem like your library does not come out of the box with what I need, but maybe you could lend a bit of advice anyway? If we figure it out and you think it would be valuable for the package, could put up a pull request.

You can access the same web view as me [here](https://www.virustotal.com/gui/file/eba1c664d265f2bbe4b4dfb466fad46c36727c63ad2ef25bc5942cd0235a0c63). As previously stated, this gives me nice family labels, i.e., [gafgyt](https://www.virustotal.com/gui/search/engines%253Agafgyt), [ddos](https://www.virustotal.com/gui/search/engines%253Addos), and [lightaidra](https://www.virustotal.com/gui/search/engines%253Alightaidra).

Using the [VirusTotal API](https://virustotal.github.io/vt-py/index.html), I can write a script like so
```python
from vt import Client

KEY = "{MY_API_KEY}"
FILE = "VirusShare_00000bd55c61bc0e490d8410db131303.elf"

client = Client(KEY)
with open(FILE, "rb") as fp:
    analysis = client.scan_file(fp, wait_for_completion=True)
results = {vendor : report["result"] for vendor, report in analysis.results.items()}
pprint(results)
```

Which gives me a pretty informative report for each vendor
<details>
  <summary>
    output
  </summary>
  {'ALYac': 'Trojan.Generic.32499050',
 'APEX': None,
 'AVG': 'ELF:Mirai-ANY [Trj]',
 'Acronis': None,
 'AhnLab-V3': 'Linux/Mirai.Gen3',
 'Alibaba': None,
 'Antiy-AVL': 'Trojan[Backdoor]/Linux.Mirai.ba',
 'Arcabit': 'Trojan.Generic.D1EFE56A',
 'Avast': 'ELF:Mirai-ANY [Trj]',
 'Avast-Mobile': 'ELF:Mirai-ANY [Trj]',
 'Avira': 'LINUX/Mirai.udhim',
 'Baidu': None,
 'BitDefender': 'Trojan.Generic.32499050',
 'BitDefenderFalx': None,
 'BitDefenderTheta': 'Gen:NN.Mirai.36722',
 'Bkav': None,
 'CAT-QuickHeal': None,
 'CMC': None,
 'ClamAV': 'Unix.Malware.Agent-6831890-0',
 'CrowdStrike': None,
 'Cybereason': None,
 'Cylance': None,
 'Cynet': 'Malicious (score: 99)',
 'Cyren': 'E32/Mirai.U.gen!Camelot',
 'DeepInstinct': None,
 'DrWeb': 'Linux.Siggen.9999',
 'ESET-NOD32': 'a variant of Linux/Mirai.AT',
 'Elastic': None,
 'Emsisoft': 'Trojan.Generic.32499050 (B)',
 'F-Secure': 'Malware.LINUX/Mirai.udhim',
 'FireEye': 'Trojan.Generic.32499050',
 'Fortinet': 'ELF/Mirai.AT!tr',
 'GData': 'Linux.Trojan.Mirai.J',
 'Google': 'Detected',
 'Gridinsoft': None,
 'Ikarus': 'Trojan.Linux.Mirai',
 'Jiangmin': 'Backdoor.Linux.asxm',
 'K7AntiVirus': None,
 'K7GW': None,
 'Kaspersky': 'HEUR:Backdoor.Linux.Mirai.ba',
 'Lionic': 'Trojan.Linux.Mirai.K!c',
 'MAX': 'malware (ai score=99)',
 'Malwarebytes': None,
 'MaxSecure': None,
 'McAfee': 'Linux/mirai.d',
 'McAfee-GW-Edition': 'Linux/mirai.d',
 'MicroWorld-eScan': 'Trojan.Generic.32499050',
 'Microsoft': 'Trojan:Linux/Mirai',
 'NANO-Antivirus': 'Trojan.ElfArm32.Mirai.fmibkd',
 'Paloalto': None,
 'Panda': None,
 'Rising': 'Backdoor.Mirai/Linux!1.BC48 (CLASSIC)',
 'SUPERAntiSpyware': None,
 'Sangfor': 'Suspicious.Linux.Save.a',
 'SentinelOne': None,
 'Sophos': 'Mal/Generic-S',
 'Symantec': 'Linux.Mirai',
 'SymantecMobileInsight': None,
 'TACHYON': None,
 'Tencent': None,
 'Trapmine': None,
 'TrendMicro': 'Trojan.Linux.MIRAI.SMNM1',
 'TrendMicro-HouseCall': 'Trojan.Linux.MIRAI.SMNM1',
 'Trustlook': None,
 'VBA32': None,
 'VIPRE': 'Trojan.Generic.32499050',
 'ViRobot': None,
 'VirIT': 'Linux.Mirai.CG',
 'Webroot': None,
 'Xcitium': 'Malware@#1ojx4ch0uqrwj',
 'Yandex': None,
 'Zillya': 'Backdoor.Mirai.Linux.48138',
 'ZoneAlarm': 'HEUR:Backdoor.Linux.Mirai.ba',
 'Zoner': None,
 'tehtris': None}
</details>

The problem is, that I don't know the processing rules by which VT takes this detailed report and condenses it down into those three family labels...If I had a comprehensive list of all the families VT classifies malware as I could just search for substrings, but I can't seem to find such a list anywhere.

**Comment by dbrennand** [comment]
Oh, @lkurlandski your example isn't using this package. You're using https://github.com/VirusTotal/vt-py which is the official VirusTotal Python package. You'll need to direct your question there for assistance with their package.

**Comment by lkurlandski** [comment]
Thumbs up.
